import type { Metadata } from "next";
import "./globals.css";
import Header from "@/ui/components/Header/Header";
import Footer from "@/ui/components/Footer/Footer";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata: Metadata = {
  title: "Sky Power – Recharge the Future",
  description: "Sky Power provides eco-friendly, high-performance rechargeable battery solutions for modern needs.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-900 text-white">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
